server:
  port: 8081  # Port where the auth service will run

spring:
  application:
    name: auth-service  # Service name

  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db  # PostgreSQL URL for auth service
    username: user_db
    password: "H@7zP!4xQw9^rS2mJf8L"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis-cache
    port: 6379
    password: "SiRT9awdH@7zP!4xQw9^rS2mJf8L"
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
eureka:
  client:
    register-with-eureka: true  # Register the auth service with Eureka
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/  # Eureka server URI
