server:
  port: 8085  # Port where the user service will run

spring:
  application:
    name: comparison-service  # Service name

  datasource:
    url: jdbc:postgresql://postgres-user:5432/comparison_db  # PostgreSQL URL for user service
    username: comparison_db
    password: comparison_password12345@@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true  # Register the service with Eureka
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/  # Eureka server URI
