server:
  port: 8084

spring:
  application:
    name: comparison-service

  datasource:
    url: jdbc:postgresql://postgres-comparison:5432/comparison_db
    username: comparison_db
    password: "H@7zP!4xQw9^rS2mJf8L"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
