server:
  port: 8087

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres-payment:5432/payment_db
    username: payment_db
    password: ${POSTGRES_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false

# RabbitMQ Configuration
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_LOGIN}
    password: ${RABBITMQ_PASSWORD}
    template:
      retry:
        enabled: true
        initial-interval: 2s
        max-attempts: 3
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3

  redis:
    host: redis-cache
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        max-wait: -1ms
# Brevo / Email configuration
brevo:
  api-key: ${BREVO_API_KEY} 
  sender:
    email: no-reply@booking-container.com
    name: Booking Container
    
# Payzone Configuration
payzone:
  merchant:
    account: ${PAYZONE_MERCHANT_ACCOUNT}
  paywall:
    secret-key: ${PAYZONE_PAYWALL_SECRET_KEY}
    url: ${PAYZONE_PAYWALL_URL}
  notification:
    key: ${PAYZONE_NOTIFICATION_KEY}
  api:
    url: ${PAYZONE_API_URL}
    key: ${PAYZONE_API_KEY}
    caller-name: ${PAYZONE_API_CALLER_NAME}

app:
  activation:
    token:
      expiry-hours: 24
  frontend:
    url: ${FRONTEND_URL:https://booking-container.com}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
