server:
  port: 8085

spring:
  application:
    name: schedule-service

  datasource:
    url: jdbc:postgresql://postgres-schedule:5432/schedule_db
    username: schedule_db
    password: H@7zP!4xQw9^rS2mJf8L
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
