server:
  port: 8084

spring:
  application:
    name: setting-service

  datasource:
    url: jdbc:postgresql://postgres-setting:5432/setting_db
    username: setting_db
    password: "H@7zP!4xQw9^rS2mJf8L"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ADD RABBITMQ CONFIGURATION HERE
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: bc.rabbit@msg.com
    password: "D8@zP!4xQw9^rS2mKf8J"
    template:
      retry:
        enabled: true
        initial-interval: 2s
        max-attempts: 3
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
