# In Config Server - user-service.yml
server:
  port: 8082  # Port where the user service will run

spring:
  application:
    name: user-service  # Service name

  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db  # PostgreSQL URL for user service
    username: user_db
    password: "H@7zP!4xQw9^rS2mJf8L"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ADD EMAIL CONFIGURATION HERE
  mail:
    host: smtp.gmail.com
    port: 587
    username: devhicham00@gmail.com
    password: xvrqfdgwqejuwuwm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

# ADD APPLICATION-SPECIFIC CONFIG
app:
  activation:
    token:
      expiry-hours: 24
  email:
    from: ${EMAIL_FROM:noreply@bc.com}
    activation-subject: "Activate Your Booking Container Account"
  frontend:
    url: ${FRONTEND_URL:https://192.168.1.202:4000}

eureka:
  client:
    register-with-eureka: true  # Register the user service with Eureka
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/  # Eureka server URI